# Generated by Django 3.2.3 on 2021-06-04 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='order date'),
            preserve_default=False,
        ),
    ]
